language: go

go:
  - 1.4
  - tip

install:
    - go get github.com/smartystreets/goconvey/...
    - go get github.com/nmcclain/ldap
    - go get github.com/goamz/goamz/...
    - go get github.com/peterbourgon/g2s/...

script: go test -v ./...
